INSERT INTO Employees(EmployeeNumber,Name,LastName,Position,Department)
VALUES
("1111","Jan","Nowak","kierownik","Marketing"),
("1112","Jakub","Kowal","kierownik","Marketing"),
("1113","Jagoda","Kowalska","kierownik","Marketing"),
("1114","Grażyna","Wojtowicz","kierownik","Marketing"),
("1115","Fabian","Frankowski","kierownik","Zakupy"),
("1116","Ewelina","Gruca","kierownik","Zakupy"),
("1117","Dorota","Giełbutowicz","kierownik","Zakupy"),
("1118","Dawid","Wójcik","junior","Marketing"),
("1119","Daniel","Wiśniewski","junior","Marketing"),
("2221","Celina","Kowalczyk","junior","Zakupy"),
("2222","Bożena","Kamińska","junior","Zakupy"),
("2223","Bolesław","Lewandowski","junior","Produkcja"),
("2224","Bogusław","Zieliński","junior","Produkcja"),
("2225","Błażej","Szymański","junior","Marketing"),
("2226","Arkadiusz","Woźniak","junior","Obsługa klienta"),
("2227","Bartosz","Dąbrowski","junior","Obsługa klienta"),
("2228","Aneta","Kozłowska","junior","Marketing"),
("2229","Alicja","Jankowska","junior","Obsługa klienta"),
("3331","Albert","Mazur","młodszy specjalista","Zakupy"),
("3332","Adam","Wojciechowski","młodszy specjalista","Marketing"),
("3333","Aga","Krawczyk","młodszy specjalista","Zakupy"),
("3334","Aga","Krawczyk","młodszy specjalista","Marketing"),
("3335","Agata","Kaczmarek","młodszy specjalista","Zakupy"),
("3336","Agnieszka","młodszy specjalista","lobortis","Zakupy"),
("3337","Jerzy","Grabowski","młodszy specjalista","Produkcja"),
("3338","Julia","Zając","młodszy specjalista","Marketing"),
("3339","Jolanta","Pawłowska","młodszy specjalista","Zakupy"),
("4441","Joanna","Pawłowska","młodszy specjalista","Produkcja"),
("4442","Kacper","Michalski","starszy specjalista","Zakupy"),
("4443","Kajetan","Michalski","starszy specjalista","Marketing"),
("4444","Kamil","Król","starszy specjalista","Marketing"),
("4445","Kamila","Wieczorek","starszy specjalista","Marketing"),
("4446","Karol","Król","starszy specjalista","Zakupy"),
("4447","Kacper","Wieczorek","starszy specjalista","Zakupy"),
("4448","Kinga","Jabłońska","regular buyer","Marketing"),
("4449","Klaudia","Wieczorek","regular buyer","Marketing"),
("5551","Klaudiusz","Nowakowski","regular buyer","Zakupy"),
("5552","Konrad","Nowakowski","regular buyer","Zakupy"),
("5553","Konrad","Nowakowski","regular buyer","Zakupy"),
("5554","Kordian","Majewski","regular buyer","Zakupy"),
("5555","Kornelia","Olszewska","regular buyer","Obsługa klienta"),
("5556","Krzysztof","Malinowski","regular buyer","Obsługa klienta"),
("5557","Laura","Pawłowska","regular buyer","Obsługa klienta"),
("5558","Lucyna","Jaworska","regular buyer","Produkcja"),
("5559","Łukasz","Jaworski","senior","Marketing"),
("6661","Maciej","Adamczyk","senior","Marketing"),
("6662","Magdalena","Dudek","senior","Marketing"),
("6663","Mariusz","Dudek","senior","Zakupy"),
("6664","Jan","Nowicki","senior","Zakupy"),
("6665","Jakub","Pawlak","senior","Zakupy"),
("6666","Jagoda","Witkowska","senior","Zakupy"),
("6667","Grażyna","Górska","senior","Marketing"),
("6668","Fabian","Walczak","senior","Zakupy"),
("6669","Ewelina","Sikora","regular","Obsługa klienta"),
("7771","Dorota","Rutkowska","senior,"Zakupy"),
("7772","Dawid","Michalak","regular","Marketing"),
("7773","Daniel","Szewczyk","regular","Marketing"),
("7774","Celina","Ostrowska","regular","Marketing"),
("7775","Bożena","Tomaszewska","regular","Marketing"),
("7776","Bolesław","Tomaszewski","regular","Produkcja"),
("7777","Bogusław","Pietrzak","regular","Produkcja"),
("7778","Błażej","Zalewski","regular","Zakupy"),
("7779","Arkadiusz","Zalewski","regular","Zakupy"),
("8881","Bartosz","Wróblewski","regular","Zakupy"),
("8882","Aneta","Marciniak","regular","Zakupy"),
("8883","Alicja","Jasińska","specjalista","Marketing"),
("8884","Albert","Zawadzki","specjalista","Marketing"),
("8885","Adam","Bąk","specjalista","Marketing"),
("8886","Ada","Jakubowska","specjalista","Marketing"),
("8887","Aga","Sadowska","specjalista","Zakupy"),
("8888","Agata","Duda","specjalista","Zakupy"),
("8889","Agnieszka","Duda","specjalista","Zakupy"),
("9991","Jerzy","Włodarczyk","specjalista","Zakupy"),
("9992","Julia","Włodarczyk","specjalista","Produkcja"),
("9993","Jolanta","Wilk","specjalista","Obsługa klienta"),
("9994","Joanna","Chmielewska","specjalista","Produkcja"),
("9995","Kacper","Borkowski","specjalista","Produkcja"),
("9996","Kajetan","Sokołowski","specjalista","Produkcja"),
("9997","Kamil","Sawicki","specjalista","Marketing"),
("9998","Kamila","Kucharska","specjalista","Marketing"),
("9999","Karol","Lis","specjalista","Produkcja"),
("0001","Kacper","Maciejewski","specjalista","Produkcja"),
("0002","Kinga","Kubiak","specjalista","Produkcja"),
("0003","Klaudia","Kalinowska","stażysta","Marketing"),
("0004","Klaudiusz","Lis","stażysta","Zakupy"),
("0005","Konrad","Mazurek","stażysta","Zakupy"),
("0006","Kornel","Wysocki","stażysta","Marketing"),
("0007","Kordian","Kołodziej","stażysta","Marketing"),
("0008","Kornelia","Kaźmierczak","stażysta","Zakupy"),
("0009","Krzysztof","Lis","stażysta","Zakupy"),
("1000","Laura","Czarnecka","stażysta","Marketing"),
("2000","Lucyna","Sobczak","stażysta","Marketing"),
("3000","Łukasz","Konieczny","stażysta","Zakupy"),
("4000","Łukasz","Konieczny","stażysta","Marketing"),
("5000","Magdalena","Urbańska","praktykant","Zakupy"),
("6000","Julia","Głowacka","praktykant","Marketing"),
("7000","Jolanta","Wasilewska","praktykant","Marketing"),
("8000","Joanna","Sikorska","praktykant","Marketing"),
("9000","Mariusz","Zakrzewski","praktykant","Zakupy"),
("1234","Dorota","Krajewska","praktykant","Marketing"),
("4321","Krzysztof","Laskowski","praktykant.","Produkcja");